--
-- Create Schema Script
--   Database Version            : 19.0.0.0.0
--   Database Compatible Level   : 19.0.0.0.0
--   Script Compatible Level     : 19.0.0.0.0
--   Toad Version                : 13.2.0.258
--   DB Connect String           : FREEPDB1
--   Schema                      : DETALES
--   Script Created by           : SYS
--   Script Created at           : 27/05/2023 09:01:33
--   Notes                       : 
--

-- Object Counts: 
--   Sequences: 51 
--   Tables: 33         Columns: 255        Constraints: 36     


-- "Set define off" turns off substitution variables.
Set define off; 

--
-- DEPARTMENTS_SEQ  (Sequence) 
--
CREATE SEQUENCE DETALES.DEPARTMENTS_SEQ
  START WITH 280
  INCREMENT BY 10
  MAXVALUE 9990
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- DEPT_SEQ  (Sequence) 
--
CREATE SEQUENCE DETALES.DEPT_SEQ
  START WITH 50
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- EMPLOYEES_SEQ  (Sequence) 
--
CREATE SEQUENCE DETALES.EMPLOYEES_SEQ
  START WITH 207
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- EMP_SEQ  (Sequence) 
--
CREATE SEQUENCE DETALES.EMP_SEQ
  START WITH 8000
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- LOCATIONS_SEQ  (Sequence) 
--
CREATE SEQUENCE DETALES.LOCATIONS_SEQ
  START WITH 3300
  INCREMENT BY 100
  MAXVALUE 9900
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_CITIES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_CITIES
  START WITH 166
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_CLIENT_SURCHARGE_GROUPS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_CLIENT_SURCHARGE_GROUPS
  START WITH 127
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_COMPANIES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_COMPANIES
  START WITH 230
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_COMPANY_EXT  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_COMPANY_EXT
  START WITH 20
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_CONTACTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_CONTACTS
  START WITH 147
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_COUNTRIES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_COUNTRIES
  START WITH 142
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_CURRENCY  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_CURRENCY
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_DB_JOB_LOG  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_DB_JOB_LOG
  START WITH 69
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_JOB_TITLES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_JOB_TITLES
  START WITH 3
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_NSCAN_ID  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_NSCAN_ID
  START WITH 156
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_ORDERS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_ORDERS
  START WITH 185
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_ORDERS_PREP  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_ORDERS_PREP
  START WITH 154
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_ORDER_DETAILS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_ORDER_DETAILS
  START WITH 1458
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_ORDER_DETAILS_PREP  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_ORDER_DETAILS_PREP
  START WITH 2283
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_ORDER_TYPES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_ORDER_TYPES
  START WITH 54
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_PHOTOS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_PHOTOS
  START WITH 34
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_PRICE_LIST_HIST  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_PRICE_LIST_HIST
  START WITH 3460
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_PRICE_LIST_IMPORTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_PRICE_LIST_IMPORTS
  START WITH 93
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_PRICE_LIST_IMPORTS_LOG  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_PRICE_LIST_IMPORTS_LOG
  START WITH 59
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_RIGHTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_RIGHTS
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_SEQ_DATA  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_SEQ_DATA
  START WITH 3
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_SFTP_CONFIGURATION  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_SFTP_CONFIGURATION
  START WITH 17
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_STATUSES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_STATUSES
  START WITH 60
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_STORAGE_PARTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_STORAGE_PARTS
  START WITH 78
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_STORAGE_SUPPLIERS_PARTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_STORAGE_SUPPLIERS_PARTS
  START WITH 19276180
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_SUPPLIERS_PARTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_SUPPLIERS_PARTS
  START WITH 5535452
  MAXVALUE 9999999999999999999999999999
  MINVALUE 50001
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_SURCHARGES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_SURCHARGES
  START WITH 56
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_SURCHARGE_BY_GROUP  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_SURCHARGE_BY_GROUP
  START WITH 212
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_SURCHARGE_GROUP  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_SURCHARGE_GROUP
  START WITH 32
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_TEMPORARY_CONTENT  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_TEMPORARY_CONTENT
  START WITH 75
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_USERS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_USERS
  START WITH 40
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_USERS_TEST  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_USERS_TEST
  START WITH 5
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_USER_GROUPS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_USER_GROUPS
  START WITH 4
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_USER_RIGHTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_USER_RIGHTS
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_VEHICLE_BRANDS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_VEHICLE_BRANDS
  START WITH 84
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_VEHICLE_MODELS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_VEHICLE_MODELS
  START WITH 114
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_CONFIRMATION_FILES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_CONFIRMATION_FILES
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_ORDER_CONFIRMATIONS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_ORDER_CONFIRMATIONS
  START WITH 93
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_ORDER_CONFIRMATIONS_DETAILS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_ORDER_CONFIRMATIONS_DETAILS
  START WITH 134
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_ORDER_CONFIRMATIONS_FILES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_ORDER_CONFIRMATIONS_FILES
  START WITH 69
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_ORDER_DETAILS_CHANGES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_ORDER_DETAILS_CHANGES
  START WITH 121
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_OVERSUPPLIED_PARTS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_OVERSUPPLIED_PARTS
  START WITH 49
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_PACKAGE_BOXES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_PACKAGE_BOXES
  START WITH 32
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_PACKAGE_BOXES_DETAILS  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_PACKAGE_BOXES_DETAILS
  START WITH 52
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_PART_SCANNING_HISTORY  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_PART_SCANNING_HISTORY
  START WITH 527
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_V_STORAGE_PLACES  (Sequence) 
--
CREATE SEQUENCE DETALES.SEQ_V_STORAGE_PLACES
  START WITH 26
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


--
-- SEQ_DATA  (Table) 
--
--   Row Count: 1
CREATE TABLE DETALES.SEQ_DATA
(
  NID             NUMBER                        DEFAULT "DETALES"."SEQ_SEQ_DATA"."NEXTVAL",
  SSEQUENCE_NAME  VARCHAR2(20 BYTE),
  NVALUE          NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- TEMPORARY_CONTENT  (Table) 
--
CREATE TABLE DETALES.TEMPORARY_CONTENT
(
  NID             NUMBER                        DEFAULT "DETALES"."SEQ_TEMPORARY_CONTENT"."NEXTVAL",
  B_BLOBCONTENT   BLOB,
  DT_INSTERTDATE  TIMESTAMP(6)                  DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- TEMP_CONTENT  (Table) 
--
--   Row Count: 0
CREATE TABLE DETALES.TEMP_CONTENT
(
  ID            NUMBER,
  FILE_CONTENT  BLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_CITIES  (Table) 
--
--   Row Count: 36
CREATE TABLE DETALES.V_CITIES
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_CITIES"."NEXTVAL" NOT NULL,
  NCOUNTRY_ID   NUMBER,
  SNAME         VARCHAR2(100 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_CLIENT_SURCHARGE_GROUPS  (Table) 
--
--   Row Count: 61
CREATE TABLE DETALES.V_CLIENT_SURCHARGE_GROUPS
(
  NCLIENT_ID     NUMBER                         DEFAULT ON NULL "DETALES"."SEQ_CLIENT_SURCHARGE_GROUPS"."NEXTVAL" NOT NULL,
  NSURCHARGE_ID  NUMBER,
  DTCREATED_AT   TIMESTAMP(6)                   DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_COMPANIES  (Table) 
--
--   Row Count: 25
CREATE TABLE DETALES.V_COMPANIES
(
  NID                      NUMBER               DEFAULT ON NULL "DETALES"."SEQ_COMPANIES"."NEXTVAL" NOT NULL,
  NTYPE                    NUMBER,
  SCOMPANY_NAME            VARCHAR2(50 BYTE),
  SEMAIL                   VARCHAR2(50 BYTE),
  SPHONE                   VARCHAR2(12 BYTE),
  SWEBSITE                 VARCHAR2(50 BYTE),
  NCOUNTRY_ID              NUMBER,
  NCITY_ID                 NUMBER,
  SCOMPANY_ADDRESS         VARCHAR2(128 BYTE),
  SSHIPPING_ADDRESS        VARCHAR2(128 BYTE),
  SZIP                     VARCHAR2(20 BYTE),
  SCOMPANY_CODE            VARCHAR2(50 BYTE),
  STAX_CODE                VARCHAR2(30 BYTE),
  NDOPAYMENTDELAYFLAG      NUMBER,
  NPAYMENT_DELAY_IN_DAYS   NUMBER,
  SCONTRACT_NUMBER         VARCHAR2(50 BYTE),
  DTCREATED_AT             TIMESTAMP(6)         DEFAULT CURRENT_TIMESTAMP,
  DTUPDATED_AT             TIMESTAMP(6),
  NHIDDEN                  NUMBER               DEFAULT ON NULL 0             NOT NULL,
  SDESCRIPTION             VARCHAR2(254 BYTE),
  SRESPONSIBLEEMPLOYEE     VARCHAR2(20 BYTE),
  NSUPPLIER_IMPORT_NUMBER  NUMBER,
  SCOMMENT                 VARCHAR2(254 BYTE),
  NCOMMENT                 NUMBER,
  SCOMPANY_NAME_SHORT      VARCHAR2(6 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_COMPANY_EXT  (Table) 
--
--   Row Count: 7
CREATE TABLE DETALES.V_COMPANY_EXT
(
  NID                NUMBER                     DEFAULT ON NULL "DETALES"."SEQ_COMPANY_EXT"."NEXTVAL" NOT NULL,
  SCOMPANY_NAME      VARCHAR2(50 BYTE),
  SEMAIL             VARCHAR2(50 BYTE),
  SWEBSITE           VARCHAR2(50 BYTE),
  SPHONE             VARCHAR2(12 BYTE),
  NCOUNTRY_ID        NUMBER,
  NCITY_ID           NUMBER,
  SCOMPANY_ADDRESS   VARCHAR2(100 BYTE),
  SSHIPPING_ADDRESS  VARCHAR2(100 BYTE),
  SZIP               VARCHAR2(20 BYTE),
  SCOMPANY_CODE      VARCHAR2(50 BYTE),
  STAX_CODE          VARCHAR2(30 BYTE),
  DTCREATED_AT       DATE                       DEFAULT SYSDATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_CONTACTS  (Table) 
--
--   Row Count: 26
CREATE TABLE DETALES.V_CONTACTS
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_CONTACTS"."NEXTVAL" NOT NULL,
  NCOMPANY_ID   NUMBER,
  SNAME         VARCHAR2(20 BYTE),
  SLAST_NAME    VARCHAR2(20 BYTE),
  SEMAIL        VARCHAR2(50 BYTE),
  SPHONE        VARCHAR2(12 BYTE),
  SJOB_TITLE    VARCHAR2(50 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_COUNTRIES  (Table) 
--
--   Row Count: 8
CREATE TABLE DETALES.V_COUNTRIES
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_COUNTRIES"."NEXTVAL" NOT NULL,
  SNAME         VARCHAR2(50 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_CURRENCY  (Table) 
--
--   Row Count: 3
CREATE TABLE DETALES.V_CURRENCY
(
  NID         NUMBER                            DEFAULT ON NULL "DETALES"."SEQ_USERS"."NEXTVAL" NOT NULL,
  SNAME       VARCHAR2(50 BYTE),
  SSHORTNAME  VARCHAR2(4 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_JOB_TITLES  (Table) 
--
CREATE TABLE DETALES.V_JOB_TITLES
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_JOB_TITLES"."NEXTVAL" NOT NULL,
  SNAME         VARCHAR2(30 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_ORDERS  (Table) 
--
--   Row Count: 54
CREATE TABLE DETALES.V_ORDERS
(
  NID            NUMBER                         DEFAULT ON NULL "DETALES"."SEQ_ORDERS"."NEXTVAL" NOT NULL,
  S_ID           VARCHAR2(20 BYTE),
  NCLIENT_ID     NUMBER,
  NCAR_ID        NUMBER,
  NSTATUS_ID     NUMBER                         DEFAULT ON NULL 4             NOT NULL,
  SVIN           VARCHAR2(20 BYTE),
  DTUPDATED_AT   DATE,
  DTCREATED_AT   DATE                           DEFAULT SYSDATE,
  NUSER_ID       NUMBER,
  NCAR_MODEL_ID  NUMBER,
  SCOMMENT       VARCHAR2(512 BYTE),
  NHIDDEN        NUMBER                         DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_ORDERS_PREP  (Table) 
--
--   Row Count: 28
CREATE TABLE DETALES.V_ORDERS_PREP
(
  NID            NUMBER                         DEFAULT ON NULL "DETALES"."SEQ_ORDERS_PREP"."NEXTVAL" NOT NULL,
  NCLIENT_ID     NUMBER,
  NCAR_ID        NUMBER,
  NCAR_MODEL_ID  NUMBER,
  SVIN           VARCHAR2(20 BYTE),
  DTCREATED_AT   DATE                           DEFAULT SYSDATE,
  NUSER_ID       NUMBER,
  DTUPDATED_AT   DATE,
  NSTATUS_ID     NUMBER                         DEFAULT 1
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_ORDER_DETAILS  (Table) 
--
--   Row Count: 449
CREATE TABLE DETALES.V_ORDER_DETAILS
(
  NID                  NUMBER                   DEFAULT ON NULL "DETALES"."SEQ_ORDER_DETAILS"."NEXTVAL" NOT NULL,
  SPART_NAME           VARCHAR2(100 BYTE),
  SPART_CODE           VARCHAR2(30 BYTE),
  NQNT                 NUMBER                   DEFAULT ON NULL 1             NOT NULL,
  NPRICE               NUMBER,
  NORDER_ID            NUMBER,
  NSUPPLIER_ID         NUMBER,
  NORDER_TYPE_ID       NUMBER,
  SPART_COMMENT        VARCHAR2(254 BYTE),
  NSTATUS_ID           NUMBER                   DEFAULT ON NULL 12            NOT NULL,
  NQNT_RETRIEVED       NUMBER                   DEFAULT 0,
  NPRICE_CHANGED       NUMBER                   DEFAULT 0,
  NCODE_CHANGED        NUMBER                   DEFAULT 0,
  NSHIPMENT_DELAYED    NUMBER                   DEFAULT 0,
  NADDITIONAL_COMMENT  NUMBER                   DEFAULT 0,
  NSURCHARGE           NUMBER                   DEFAULT 0,
  NINOVICE_COUNT       NUMBER                   DEFAULT 0,
  NQNT_CONFIRMED       NUMBER(8),
  NQNT_PACKED          NUMBER                   DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_ORDER_DETAILS_CHANGES  (Table) 
--
--   Row Count: 61
CREATE TABLE DETALES.V_ORDER_DETAILS_CHANGES
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_V_ORDER_DETAILS_CHANGES"."NEXTVAL" NOT NULL,
  NPART_ID      NUMBER,
  SCOMMENT      VARCHAR2(256 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP,
  NTYPE         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_ORDER_DETAILS_PREP  (Table) 
--
--   Row Count: 115
CREATE TABLE DETALES.V_ORDER_DETAILS_PREP
(
  NID             NUMBER                        DEFAULT "DETALES"."SEQ_ORDER_DETAILS_PREP"."NEXTVAL",
  SPART_NAME      VARCHAR2(100 BYTE),
  SPART_CODE      VARCHAR2(30 BYTE),
  NPRICE          NUMBER,
  NORDER_ID       NUMBER,
  NSUPPLIER_ID    NUMBER,
  NORDER_TYPE_ID  NUMBER,
  SPART_COMMENT   VARCHAR2(254 BYTE),
  NQNT            NUMBER                        DEFAULT 1,
  DTCREATED_AT    TIMESTAMP(6)                  DEFAULT current_timestamp,
  SELECTED        NUMBER                        DEFAULT 1,
  SORDER_ID       VARCHAR2(50 BYTE),
  NSURCHARGE      NUMBER                        DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_ORDER_TYPES  (Table) 
--
--   Row Count: 21
CREATE TABLE DETALES.V_ORDER_TYPES
(
  NID             NUMBER                        DEFAULT ON NULL "DETALES"."SEQ_ORDER_TYPES"."NEXTVAL" NOT NULL,
  NSUPPLIER_ID    NUMBER,
  SNAME           VARCHAR2(20 BYTE),
  NDELIVERY_DAYS  NUMBER,
  DTUPDATED_AT    TIMESTAMP(6),
  DTCREATED_AT    TIMESTAMP(6)                  DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_OVERSUPPLIED_PARTS  (Table) 
--
--   Row Count: 17
CREATE TABLE DETALES.V_OVERSUPPLIED_PARTS
(
  NID            NUMBER                         DEFAULT ON NULL "DETALES"."SEQ_V_OVERSUPPLIED_PARTS"."NEXTVAL" NOT NULL,
  NCAR_ID        NUMBER,
  NSUPPLIER_ID   NUMBER,
  SCODE          VARCHAR2(50 BYTE),
  NPRICE         NUMBER,
  NQNT           NUMBER,
  NSTATUS_ID     NUMBER                         DEFAULT ON NULL 26            NOT NULL,
  SCOMMENT       VARCHAR2(254 BYTE),
  DTCREATED_AT   TIMESTAMP(6)                   DEFAULT CURRENT_TIMESTAMP,
  NIS_ACCOUNTED  NUMBER                         DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_PART_SCANNING_HISTORY  (Table) 
--
--   Row Count: 319
CREATE TABLE DETALES.V_PART_SCANNING_HISTORY
(
  NID              NUMBER                       DEFAULT "DETALES"."SEQ_V_PART_SCANNING_HISTORY"."NEXTVAL",
  NPART_ID         VARCHAR2(100 BYTE),
  NQNT             NUMBER,
  NORDER_ID        NUMBER,
  NUSER_ID         NUMBER,
  DTCREATION_DATE  DATE                         DEFAULT ON NULL current_timestamp NOT NULL,
  NSTATUS          NUMBER                       DEFAULT 1,
  SPART_CODE       VARCHAR2(100 BYTE),
  NSUPPLIER_ID     NUMBER,
  NSCAN_ID         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_PHOTOS  (Table) 
--
--   Row Count: 11
CREATE TABLE DETALES.V_PHOTOS
(
  NID             NUMBER                        DEFAULT ON NULL "DETALES"."SEQ_PHOTOS"."NEXTVAL" NOT NULL,
  NPART_ID        NUMBER,
  BLPHOTO         BLOB,
  SMIME_TYPE      VARCHAR2(30 BYTE),
  SFILE_NAME      VARCHAR2(256 BYTE),
  DTLAST_UPDATED  DATE                          DEFAULT SYSDATE,
  NDOC_SIZE       NUMBER,
  DTCREATED_AT    TIMESTAMP(6)                  DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_PRICE_LIST_IMPORTS  (Table) 
--
--   Row Count: 18
CREATE TABLE DETALES.V_PRICE_LIST_IMPORTS
(
  NID                NUMBER                     DEFAULT ON NULL "DETALES"."SEQ_PRICE_LIST_IMPORTS"."NEXTVAL" NOT NULL,
  NCAR_ID            NUMBER,
  NSUPPLIER_ID       NUMBER,
  NORDER_TYPE_ID     NUMBER,
  DTIMPORT_DATE      DATE                       DEFAULT ON NULL SYSDATE       NOT NULL,
  DTEXPIRATION_DATE  DATE,
  SFILENAME          VARCHAR2(254 BYTE),
  NAPPROVED          NUMBER,
  NHASERRORS         NUMBER                     DEFAULT NULL,
  DTCREATED_AT       TIMESTAMP(6)               DEFAULT CURRENT_TIMESTAMP,
  NFILE_ID           NUMBER,
  NIMPORT_STARTED    NUMBER                     DEFAULT 0,
  NMERGE_BOOL        NUMBER                     DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_RIGHTS  (Table) 
--
CREATE TABLE DETALES.V_RIGHTS
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_USERS"."NEXTVAL" NOT NULL,
  SNAME         VARCHAR2(50 BYTE),
  SDESCRIPTION  VARCHAR2(254 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP,
  DTUPDATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_STATUSES  (Table) 
--
--   Row Count: 24
CREATE TABLE DETALES.V_STATUSES
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_STATUSES"."NEXTVAL" NOT NULL,
  SNAME         VARCHAR2(50 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP,
  NTYPE         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_STORAGE_PARTS  (Table) 
--
--   Row Count: 26
CREATE TABLE DETALES.V_STORAGE_PARTS
(
  NID                NUMBER                     DEFAULT ON NULL "DETALES"."SEQ_STORAGE_PARTS"."NEXTVAL" NOT NULL,
  SNAME              VARCHAR2(100 BYTE),
  SCODE              VARCHAR2(30 BYTE),
  NCAR_ID            NUMBER,
  NCAR_MODEL_ID      NUMBER,
  NPRICE             NUMBER,
  NLENGTH            NUMBER,
  NWIDTH             NUMBER,
  NHEIGHT            NUMBER,
  NWEIGHT            NUMBER,
  SDESCRIPTION       VARCHAR2(254 BYTE),
  NACCOUNTINGFLAG    NUMBER                     DEFAULT 0,
  DTCREATED_AT       TIMESTAMP(6)               DEFAULT CURRENT_TIMESTAMP,
  NQNT               NUMBER                     DEFAULT 1,
  NORIGINAL_PACKAGE  NUMBER                     DEFAULT 0,
  NSECTION_ID        NUMBER                     DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_STORAGE_PLACES  (Table) 
--
--   Row Count: 8
CREATE TABLE DETALES.V_STORAGE_PLACES
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_V_STORAGE_PLACES"."NEXTVAL" NOT NULL,
  SNAME         VARCHAR2(30 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_STORAGE_SUPPLIERS_PARTS  (Table) 
--
--   Row Count: 2065853
CREATE TABLE DETALES.V_STORAGE_SUPPLIERS_PARTS
(
  NID             NUMBER                        DEFAULT ON NULL "DETALES"."SEQ_STORAGE_SUPPLIERS_PARTS"."NEXTVAL" NOT NULL,
  NCAR_ID         NUMBER,
  NSUPPLIER_ID    NUMBER,
  NORDER_TYPE_ID  NUMBER,
  SCODE           VARCHAR2(30 BYTE),
  SNAME           VARCHAR2(100 BYTE),
  NPRICE          NUMBER,
  SCHILD_CODE     VARCHAR2(30 BYTE),
  NHEIGHT         NUMBER,
  NWIDTH          NUMBER,
  NLENGTH         NUMBER,
  NWEIGHT         NUMBER,
  DTCREATED_AT    TIMESTAMP(6)                  DEFAULT CURRENT_TIMESTAMP,
  DTUPDATED_AT    TIMESTAMP(6),
  NQNT            NUMBER                        DEFAULT 1
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_SUPPLIERS_PARTS_LOG  (Table) 
--
--   Row Count: 2572
CREATE TABLE DETALES.V_SUPPLIERS_PARTS_LOG
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_SUPPLIERS_PARTS"."NEXTVAL" NOT NULL,
  NIMPORT_ID    NUMBER,
  NROW_NUMBER   NUMBER,
  SMESSAGE      VARCHAR2(254 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_SURCHARGES  (Table) 
--
--   Row Count: 17
CREATE TABLE DETALES.V_SURCHARGES
(
  NID                NUMBER                     DEFAULT ON NULL "DETALES"."SEQ_SURCHARGES"."NEXTVAL" NOT NULL,
  NVEHICLE_BRAND_ID  NUMBER,
  NORDER_TYPE_ID     NUMBER,
  NCLIENT_ID         NUMBER,
  NPRICE             NUMBER,
  DTCREATED_AT       TIMESTAMP(6)               DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_SURCHARGE_BY_GROUP  (Table) 
--
--   Row Count: 82
CREATE TABLE DETALES.V_SURCHARGE_BY_GROUP
(
  NID                  NUMBER                   DEFAULT ON NULL "DETALES"."SEQ_SURCHARGE_BY_GROUP"."NEXTVAL" NOT NULL,
  NVEHICLE_BRAND_ID    NUMBER,
  NORDER_TYPE_ID       NUMBER,
  NSURCHARGE_GROUP_ID  NUMBER,
  NPRICE               NUMBER,
  DTCREATED_AT         TIMESTAMP(6)             DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_SURCHARGE_GROUP  (Table) 
--
--   Row Count: 4
CREATE TABLE DETALES.V_SURCHARGE_GROUP
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_SURCHARGE_GROUP"."NEXTVAL" NOT NULL,
  SNAME         VARCHAR2(50 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_USERS  (Table) 
--
--   Row Count: 4
CREATE TABLE DETALES.V_USERS
(
  ID           NUMBER                           DEFAULT ON NULL "DETALES"."SEQ_USERS"."NEXTVAL" NOT NULL,
  USER_NAME    VARCHAR2(50 BYTE),
  FIRST_NAME   VARCHAR2(50 BYTE),
  LAST_NAME    VARCHAR2(50 BYTE),
  PASSWORD     VARCHAR2(100 BYTE),
  ISADMIN      NUMBER                           DEFAULT 0,
  GROUP_ID     NUMBER,
  UPDATED_AT   TIMESTAMP(6)                     DEFAULT CURRENT_TIMESTAMP,
  CREATED_AT   TIMESTAMP(6)                     DEFAULT CURRENT_TIMESTAMP,
  ISSUSPENDED  NUMBER                           DEFAULT 0                     NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_VEHICLE_BRANDS  (Table) 
--
--   Row Count: 29
CREATE TABLE DETALES.V_VEHICLE_BRANDS
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_VEHICLE_BRANDS"."NEXTVAL" NOT NULL,
  SNAME         VARCHAR2(30 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


--
-- V_VEHICLE_MODELS  (Table) 
--
--   Row Count: 24
CREATE TABLE DETALES.V_VEHICLE_MODELS
(
  NID           NUMBER                          DEFAULT ON NULL "DETALES"."SEQ_VEHICLE_MODELS"."NEXTVAL" NOT NULL,
  NCAR_ID       NUMBER,
  SNAME         VARCHAR2(30 BYTE),
  DTCREATED_AT  TIMESTAMP(6)                    DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
